workflows:
  ios-ad-hoc:
    name: iOS Ad Hoc Build (Final Deployment Fix)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Force Deployment Target in Project Files
        script: |
          # 1. تعديل ملف المشروع لضبط الإصدار 13.0 كحد أدنى في كل مكان
          find . -name "project.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' {} +
          
          # 2. تعديل الـ Podfile لإجبار جميع المكتبات (بما فيها Firebase) على 13.0
          # سنقوم بإضافة سطر في بداية الـ Podfile لضمان التوافق
          sed -i '' "1s/.*/platform :ios, '13.0'/" ios/Podfile

      - name: Update CocoaPods
        script: |
          cd ios
          # تنظيف شامل
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData
          
          # تثبيت المكتبات مع تحديث المستودع
          pod install --repo-update
          
      - name: Create ExportOptions.plist
        script: |
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
      - name: Manual Xcode Build
        script: |
          flutter build ios --release --no-codesign
          
          cd ios
          xcodebuild archive \
                     -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration "Release-production" \
                     -archivePath build/Runner.xcarchive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     PROVISIONING_PROFILE="" \
                     IPHONEOS_DEPLOYMENT_TARGET=13.0

          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist ExportOptions.plist \
                     CODE_SIGNING_ALLOWED=NO
                     
    artifacts:
      - ios/build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - alhajamekh@gmail.com