// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU8dph-nH7OmPwAxyQlk9BjmEMstKrLbI',
    appId: '1:884990344289:android:2de58d37b3df8bb3153e20',
    messagingSenderId: '884990344289',
    projectId: 'ymtaz-51895',
    storageBucket: 'ymtaz-51895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjqLmpT_qzu3Uoj-ESCQcAzgII1w4tzJM',
    appId: '1:884990344289:ios:ed3e463d5337d586153e20',
    messagingSenderId: '884990344289',
    projectId: 'ymtaz-51895',
    storageBucket: 'ymtaz-51895.appspot.com',
    androidClientId: '884990344289-b2bpjdub19isqineflujll007deru70f.apps.googleusercontent.com',
    iosClientId: '884990344289-otaj32g2ai29pivtvlab64u2slae4qp3.apps.googleusercontent.com',
    iosBundleId: 'com.ymtaz.ymtaz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeCOpGjSa5pT1dRzNVCPp0XEC3Gk51t48',
    appId: '1:884990344289:web:08acc7273170ce46153e20',
    messagingSenderId: '884990344289',
    projectId: 'ymtaz-51895',
    authDomain: 'ymtaz-51895.firebaseapp.com',
    storageBucket: 'ymtaz-51895.appspot.com',
    measurementId: 'G-MYVZVHRKY2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjqLmpT_qzu3Uoj-ESCQcAzgII1w4tzJM',
    appId: '1:884990344289:ios:b6d9699abcfa446f153e20',
    messagingSenderId: '884990344289',
    projectId: 'ymtaz-51895',
    storageBucket: 'ymtaz-51895.appspot.com',
    androidClientId: '884990344289-b2bpjdub19isqineflujll007deru70f.apps.googleusercontent.com',
    iosClientId: '884990344289-fprenhpogsu528flnco897ua1pvu1o7s.apps.googleusercontent.com',
    iosBundleId: 'com.ymtaz.yamtaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-6WBKNqP_zVF-D_EzGr4G1dOmWfpNLB4',
    appId: '1:884990344289:web:d5e6d3d7b81a9210153e20',
    messagingSenderId: '884990344289',
    projectId: 'ymtaz-51895',
    authDomain: 'ymtaz-51895.firebaseapp.com',
    storageBucket: 'ymtaz-51895.appspot.com',
    measurementId: 'G-GDETVCHKS2',
  );

}